package com.fastazz.dragontiger;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.view.*;
import android.widget.*;
import java.util.*;

public class CardMainActivity extends Activity {
    static final String PREF="rounds";
    static final String[] RANKS={"A","2","3","4","5","6","7","8","9","10","J","Q","K"};
    static final String[] SUITS={"♠","♥","♣","♦"};
    static final String INITIAL="__DATA__";
    ArrayList<Round> rounds=new ArrayList<>();
    Button dragonBtn,tigerBtn; TextView prediction,numberPrediction,stats,lastResults,patternText,patternAnalysis,transitionText,countText,topStats;
    String dragonCard="A♠",tigerCard="A♥",selectedDragonRank="A",selectedTigerRank="A";
    static class Round {String d,t,r; Round(String d,String t,String r){this.d=d;this.t=t;this.r=r;}}
    @Override public void onCreate(Bundle b){super.onCreate(b);load();ui();render();}
    TextView text(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(Color.WHITE);v.setPadding(10,8,10,8);return v;}
    GradientDrawable bg(int c,int s){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(18);g.setStroke(2,s);return g;}
    LinearLayout panel(){LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(12,12,12,12);p.setBackground(bg(Color.rgb(6,40,68),Color.CYAN));LinearLayout.LayoutParams q=new LinearLayout.LayoutParams(-1,-2);q.setMargins(0,8,0,0);p.setLayoutParams(q);return p;}
    void ui(){
      ScrollView sv=new ScrollView(this);sv.setBackgroundColor(Color.rgb(3,18,32));LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(10,10,10,20);sv.addView(root);
      TextView title=text("DRAGON TIGER\nPREDICTION",27);title.setGravity(Gravity.CENTER);title.setTypeface(null,Typeface.BOLD);title.setTextColor(Color.CYAN);root.addView(title);
      countText=text("",14);countText.setGravity(Gravity.CENTER);root.addView(countText);topStats=text("",14);topStats.setGravity(Gravity.CENTER);topStats.setBackground(bg(Color.rgb(8,55,90),Color.MAGENTA));root.addView(topStats);
      LinearLayout pp=panel();pp.addView(text("HISTORICAL RESULT ANALYSIS",18));prediction=text("",20);prediction.setGravity(Gravity.CENTER);prediction.setTypeface(null,Typeface.BOLD);pp.addView(prediction);root.addView(pp);
      LinearLayout cp=panel();cp.addView(text("PLAYING CARD • A TO K • 52 CARDS",18));cp.addView(text("Select Dragon and Tiger card. Winner is automatic: A=1 ... K=13.",12));LinearLayout sides=new LinearLayout(this);sides.setOrientation(LinearLayout.HORIZONTAL);dragonBtn=side("DRAGON\n"+dragonCard,Color.CYAN);tigerBtn=side("TIGER\n"+tigerCard,Color.rgb(255,179,0));sides.addView(dragonBtn,new LinearLayout.LayoutParams(0,105,1));LinearLayout.LayoutParams tl=new LinearLayout.LayoutParams(0,105,1);tl.setMargins(8,0,0,0);sides.addView(tigerBtn,tl);cp.addView(sides);dragonBtn.setOnClickListener(v->picker(true));tigerBtn.setOnClickListener(v->picker(false));Button add=new Button(this);add.setText("ADD RESULT • AUTO WINNER");cp.addView(add);add.setOnClickListener(v->addAuto());root.addView(cp);
      LinearLayout ep=panel();ep.addView(text("EDIT RESULT",18));Button edit=new Button(this);edit.setText("EDIT SAVED ROUND");ep.addView(edit);edit.setOnClickListener(v->editRound());root.addView(ep);
      LinearLayout lp=panel();lp.addView(text("LAST RESULTS • NEWEST ON LEFT",18));lastResults=text("",15);lastResults.setGravity(Gravity.CENTER);lp.addView(lastResults);root.addView(lp);
      LinearLayout pat=panel();pat.addView(text("D/T PATTERN FINDER",18));EditText input=new EditText(this);input.setHint("Example: DDTTDDTT or DTDTDT");input.setTextColor(Color.WHITE);input.setHintTextColor(Color.LTGRAY);input.setSingleLine(true);pat.addView(input);Button find=new Button(this);find.setText("FIND EXACT PATTERN");pat.addView(find);patternAnalysis=text("Enter D/T pattern to search historical rounds.",14);pat.addView(patternAnalysis);find.setOnClickListener(v->findPattern(input.getText().toString()));root.addView(pat);
      LinearLayout p3=panel();p3.addView(text("CURRENT 3-RESULT PATTERN • NEWEST → OLDEST",18));patternText=text("",18);patternText.setGravity(Gravity.CENTER);patternText.setTextColor(Color.CYAN);p3.addView(patternText);root.addView(p3);
      LinearLayout np=panel();np.addView(text("NUMBER ANALYSIS • A TO K",18));numberPrediction=text("",14);np.addView(numberPrediction);root.addView(np);
      LinearLayout sp=panel();sp.addView(text("STATISTICS",18));stats=text("",14);sp.addView(stats);root.addView(sp);LinearLayout tp=panel();tp.addView(text("CARD TRANSITION ANALYSIS",18));transitionText=text("",14);tp.addView(transitionText);root.addView(tp);
      LinearLayout ap=panel();ap.addView(text("DATA CONTROL",18));Button bulk=new Button(this);bulk.setText("UPLOAD EXCEL / CSV (BULK DATA)");ap.addView(bulk);bulk.setOnClickListener(v->startActivity(new Intent(this,ImportActivity.class)));Button clear=new Button(this);clear.setText("CLEAR SAVED ROUNDS");ap.addView(clear);clear.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Clear saved rounds?").setMessage("Clear imported/manual rounds and restore the built-in 505 reference?").setPositiveButton("CLEAR",(d,w)->{rounds.clear();getSharedPreferences("MainActivity_preferences",MODE_PRIVATE).edit().remove(PREF).apply();load();render();}).setNegativeButton("CANCEL",null).show());root.addView(ap);
      TextView note=text("Historical reference only. It does not guarantee the next result.",12);note.setGravity(Gravity.CENTER);root.addView(note);setContentView(sv);
    }
    Button side(String s,int c){Button b=new Button(this);b.setText(s);b.setTextSize(18);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setTypeface(null,Typeface.BOLD);b.setBackground(bg(Color.rgb(10,70,112),c));return b;}
    int value(String r){if("A".equals(r))return 1;if("J".equals(r))return 11;if("Q".equals(r))return 12;if("K".equals(r))return 13;try{return Integer.parseInt(r);}catch(Exception e){return 0;}}
    String autoWinner(){int a=value(selectedDragonRank),b=value(selectedTigerRank);return a>b?"D":b>a?"T":"SAME";}
    void picker(boolean isDragon){ScrollView sv=new ScrollView(this);GridLayout g=new GridLayout(this);g.setColumnCount(4);sv.addView(g);AlertDialog box=new AlertDialog.Builder(this).setTitle((isDragon?"DRAGON":"TIGER")+" • SELECT CARD").setView(sv).create();for(String r:RANKS)for(String s:SUITS){String card=r+s;Button b=new Button(this);b.setText(r+"\n"+s);b.setTextSize(15);b.setAllCaps(false);boolean red=s.equals("♥")||s.equals("♦");b.setTextColor(red?Color.rgb(210,25,35):Color.BLACK);b.setBackground(bg(Color.WHITE,red?Color.RED:Color.DKGRAY));GridLayout.LayoutParams q=new GridLayout.LayoutParams();q.width=76;q.height=80;q.setMargins(3,3,3,3);g.addView(b,q);b.setOnClickListener(v->{if(isDragon){dragonCard=card;selectedDragonRank=r;dragonBtn.setText("DRAGON\n"+card);}else{tigerCard=card;selectedTigerRank=r;tigerBtn.setText("TIGER\n"+card);}box.dismiss();});}box.show();}
    void addAuto(){rounds.add(new Round(selectedDragonRank,selectedTigerRank,autoWinner()));save();render();}
    void editRound(){if(rounds.isEmpty())return;String[] items=new String[rounds.size()];for(int i=rounds.size()-1;i>=0;i--){Round x=rounds.get(i);items[rounds.size()-1-i]=(i+1)+" : "+x.d+" vs "+x.t+" = "+label(x.r);}new AlertDialog.Builder(this).setTitle("SELECT ROUND TO EDIT").setItems(items,(d,which)->editCards(rounds.size()-1-which)).show();}
    void editCards(int idx){Round old=rounds.get(idx);selectedDragonRank=old.d;selectedTigerRank=old.t;LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);Button db=side("DRAGON\n"+old.d,Color.CYAN),tb=side("TIGER\n"+old.t,Color.rgb(255,179,0));p.addView(db);p.addView(tb);TextView w=text("AUTO RESULT: "+label(autoWinner()),18);p.addView(w);db.setOnClickListener(v->pickerEdit(true,db,tb,w));tb.setOnClickListener(v->pickerEdit(false,db,tb,w));new AlertDialog.Builder(this).setTitle("EDIT ROUND "+(idx+1)).setView(p).setPositiveButton("SAVE",(x,y)->{rounds.set(idx,new Round(selectedDragonRank,selectedTigerRank,autoWinner()));save();render();}).setNegativeButton("CANCEL",null).show();}
    void pickerEdit(boolean isDragon,Button db,Button tb,TextView w){ScrollView sv=new ScrollView(this);GridLayout g=new GridLayout(this);g.setColumnCount(4);sv.addView(g);AlertDialog box=new AlertDialog.Builder(this).setTitle("SELECT CARD").setView(sv).create();for(String r:RANKS)for(String s:SUITS){String card=r+s;Button b=new Button(this);b.setText(r+"\n"+s);boolean red=s.equals("♥")||s.equals("♦");b.setTextColor(red?Color.RED:Color.BLACK);b.setBackground(bg(Color.WHITE,red?Color.RED:Color.DKGRAY));GridLayout.LayoutParams q=new GridLayout.LayoutParams();q.width=76;q.height=80;q.setMargins(3,3,3,3);g.addView(b,q);b.setOnClickListener(v->{if(isDragon){selectedDragonRank=r;db.setText("DRAGON\n"+card);}else{selectedTigerRank=r;tb.setText("TIGER\n"+card);}w.setText("AUTO RESULT: "+label(autoWinner()));box.dismiss();});}box.show();}
    void findPattern(String raw){String target=raw.toUpperCase(Locale.US).replaceAll("[^DT]","");if(target.length()==0){patternAnalysis.setText("Use only D and T, example DDTTDDTT.");return;}int hits=0;StringBuilder where=new StringBuilder();int total=rounds.size();for(int end=total-1;end>=target.length()-1;end--){StringBuilder s=new StringBuilder();for(int k=0;k<target.length();k++)s.append(shortR(rounds.get(end-k).r));if(s.toString().equals(target)){hits++;if(where.length()>0)where.append(", ");where.append(end+1+"→"+(end-target.length()+2));}}patternAnalysis.setText("Pattern: "+target+"\nExact matches: "+hits+"\nNewest→oldest rounds: "+(hits==0?"None":where)+"\nTie is ignored in D/T pattern matching.");}
    void load(){String s=getSharedPreferences("MainActivity_preferences",MODE_PRIVATE).getString(PREF,"");if(!s.isEmpty()){parse(s);return;}for(String x:INITIAL.split(";")){String[] a=x.split(",");if(a.length==4)rounds.add(new Round(a[1],a[2],a[3]));}save();}
    void parse(String s){for(String x:s.split(";")){String[] a=x.split(",");if(a.length==4)rounds.add(new Round(a[1],a[2],a[3]));else if(a.length==3)rounds.add(new Round(a[0],a[1],a[2]));}}
    void save(){StringBuilder s=new StringBuilder();int n=1;for(Round x:rounds){if(s.length()>0)s.append(";");s.append(n++).append(",").append(x.d).append(",").append(x.t).append(",").append(x.r);}getSharedPreferences("MainActivity_preferences",MODE_PRIVATE).edit().putString(PREF,s.toString()).apply();}
    String label(String r){return "SAME".equals(r)?"TIE":r;}String shortR(String r){return "D".equals(r)?"D":"T".equals(r)?"T":"E";}String pct(int n,int z){return z==0?"0.0":String.format(Locale.US,"%.1f",n*100.0/z);}
    void render(){int total=rounds.size();countText.setText("HISTORICAL ROUNDS: "+total+" • NEWEST ON LEFT");if(total==0){prediction.setText("NO DATA");return;}int d=0,t=0,e=0,pair=0;for(Round x:rounds){if("D".equals(x.r))d++;else if("T".equals(x.r))t++;else e++;if(x.d.equals(x.t))pair++;}topStats.setText("DRAGON "+d+" | TIE "+e+" | TIGER "+t+" | PAIR "+pair);prediction.setText("Dragon "+pct(d,total)+"% | Tie "+pct(e,total)+"% | Tiger "+pct(t,total)+"%\nHistorical frequency: "+(d>=t?"Dragon":"Tiger"));stats.setText("Dragon: "+d+" ("+pct(d,total)+"%)\nTie: "+e+" ("+pct(e,total)+"%)\nTiger: "+t+" ("+pct(t,total)+"%)\nPair: "+pair+" ("+pct(pair,total)+"%)");StringBuilder lr=new StringBuilder();for(int k=0;k<Math.min(10,total);k++){if(k>0)lr.append(" | ");lr.append(total-k).append(" ").append(label(rounds.get(total-1-k).r));}lastResults.setText(lr.toString());StringBuilder p=new StringBuilder();for(int k=0;k<Math.min(3,total);k++){if(k>0)p.append(" → ");p.append(shortR(rounds.get(total-1-k).r));}patternText.setText(p.toString());int[] dc=new int[13],tc=new int[13];for(Round x:rounds){int a=value(x.d),b=value(x.t);if(a>=1&&a<=13)dc[a-1]++;if(b>=1&&b<=13)tc[b-1]++;}StringBuilder nb=new StringBuilder("Dragon card frequency | Tiger card frequency\n");for(int i=0;i<13;i++)nb.append(RANKS[i]).append(": ").append(dc[i]).append(" (").append(pct(dc[i],total)).append("%) | ").append(tc[i]).append(" (").append(pct(tc[i],total)).append("%)\n");numberPrediction.setText(nb.toString());Round latest=rounds.get(total-1);int tr=0,nd=0,nt=0,ne=0;for(int i=total-1;i>0;i--)if(rounds.get(i).d.equals(latest.d)){tr++;String r=rounds.get(i-1).r;if("D".equals(r))nd++;else if("T".equals(r))nt++;else ne++;}transitionText.setText("Latest Dragon rank: "+latest.d+"\nHistorical older-result frequency: "+(tr==0?"No data":"Dragon "+pct(nd,tr)+"% | Tie "+pct(ne,tr)+"% | Tiger "+pct(nt,tr)+"%"));}
    @Override protected void onResume(){super.onResume();if(lastResults!=null){rounds.clear();load();render();}}
}
