package com.fastazz.dragontiger;

import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.widget.*;import java.util.*;

public class CardMainActivity extends Activity{
 String[] ranks={"A","2","3","4","5","6","7","8","9","10","J","Q","K"}; String[] suits={"♠","♥","♣","♦"};
 Button dragon,tiger; TextView prediction,stats; int d=0,t=0,tie=0;
 public void onCreate(Bundle b){super.onCreate(b);ui();}
 TextView text(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(Color.WHITE);v.setPadding(10,8,10,8);return v;}
 GradientDrawable bg(int c,int stroke){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(18);g.setStroke(2,stroke);return g;}
 void ui(){ScrollView sv=new ScrollView(this);sv.setBackgroundColor(Color.rgb(3,18,32));LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(10,10,10,20);sv.addView(root);
 TextView title=text("DRAGON TIGER\nPREDICTION",27);title.setGravity(17);title.setTypeface(null,1);title.setTextColor(Color.CYAN);root.addView(title);
 LinearLayout top=new LinearLayout(this);top.setOrientation(LinearLayout.HORIZONTAL);String[] n={"DRAGON\n0","TIE\n0","TIGER\n0","PAIR\n0"};int[] c={Color.CYAN,Color.LTGRAY,Color.rgb(255,179,0),Color.MAGENTA};for(int i=0;i<4;i++){TextView v=text(n[i],14);v.setGravity(17);v.setTypeface(null,1);v.setBackground(bg(Color.rgb(8,55,90),c[i]));top.addView(v,new LinearLayout.LayoutParams(0,78,1));}root.addView(top);
 LinearLayout p=panel();p.addView(text("NEXT RESULT PREDICTION",19));prediction=text("WAITING FOR DATA",23);prediction.setGravity(17);prediction.setTypeface(null,1);p.addView(prediction);root.addView(p);
 LinearLayout cards=panel();cards.addView(text("SELECT PLAYING CARD",20));cards.addView(text("Tap a side to select from all 52 cards • Red / Black suits",13));LinearLayout cr=new LinearLayout(this);cr.setOrientation(LinearLayout.HORIZONTAL);dragon=side("DRAGON\nA♠",Color.CYAN);tiger=side("TIGER\nA♥",Color.rgb(255,179,0));cr.addView(dragon,new LinearLayout.LayoutParams(0,125,1));LinearLayout lp=new LinearLayout.LayoutParams(0,125,1);lp.setMargins(8,0,0,0);cr.addView(tiger,lp);cards.addView(cr);dragon.setOnClickListener(v->picker(true));tiger.setOnClickListener(v->picker(false));root.addView(cards);
 LinearLayout res=panel();res.addView(text("LAST RESULT",16));LinearLayout rr=new LinearLayout(this);for(String x:new String[]{"DRAGON","TIE","TIGER"}){Button b=new Button(this);b.setText(x);rr.addView(b,new LinearLayout.LayoutParams(0,58,1));b.setOnClickListener(v->{if(x.equals("DRAGON"))d++;else if(x.equals("TIGER"))t++;else tie++;render();});}res.addView(rr);root.addView(res);
 stats=text("STATISTICS\nDragon 0% | Tie 0% | Tiger 0%",15);stats.setBackground(bg(Color.rgb(8,45,72),Color.CYAN));root.addView(stats);TextView note=text("Historical analysis only. It does not guarantee the next result.",13);note.setGravity(17);root.addView(note);setContentView(sv);}
 LinearLayout panel(){LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(12,12,12,12);p.setBackground(bg(Color.rgb(6,40,68),Color.CYAN));return p;}
 Button side(String s,int c){Button b=new Button(this);b.setText(s);b.setTextSize(19);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setTypeface(null,1);b.setBackground(bg(Color.rgb(10,70,112),c));return b;}
 void picker(boolean isDragon){GridLayout g=new GridLayout(this);g.setColumnCount(4);g.setPadding(5,5,5,5);g.setBackgroundColor(Color.rgb(3,18,30));AlertDialog box=new AlertDialog.Builder(this).setTitle((isDragon?"DRAGON":"TIGER")+" • SELECT CARD").setView(g).create();for(String r:ranks)for(String s:suits){String card=r+s;Button b=new Button(this);b.setText(r+"\n"+s);b.setTextSize(17);b.setAllCaps(false);boolean red=s.equals("♥")||s.equals("♦");b.setTextColor(red?Color.rgb(210,25,35):Color.BLACK);b.setBackground(bg(Color.WHITE,red?Color.RED:Color.DKGRAY));GridLayout.LayoutParams q=new GridLayout.LayoutParams();q.width=145;q.height=100;q.setMargins(3,3,3,3);g.addView(b,q);b.setOnClickListener(v->{if(isDragon)dragon.setText("DRAGON\n"+card);else tiger.setText("TIGER\n"+card);box.dismiss();});}box.show();}
 void render(){int total=d+t+tie;if(total==0){prediction.setText("WAITING FOR DATA");stats.setText("STATISTICS\nDragon 0% | Tie 0% | Tiger 0%");return;}String p=d>=t?"DRAGON":"TIGER";double pc=Math.max(d,t)*100.0/total;prediction.setText(p+"\nHistorical frequency: "+String.format(Locale.US,"%.1f",pc)+"%\nBased on "+total+" results");stats.setText(String.format(Locale.US,"STATISTICS\nDragon %.1f%% (%d) | Tie %.1f%% (%d) | Tiger %.1f%% (%d)",d*100.0/total,d,tie*100.0/total,tie,t*100.0/total,t));}
}