package com.fastazz.dragontiger;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.widget.*;import java.io.*;import java.util.*;

public class CardDashboardActivity extends Activity{
 static final String P="MainActivity_preferences",K="rounds";static final String[] R={"A","2","3","4","5","6","7","8","9","10","J","Q","K"};static final String[] S={"♠","♥","♣","♦"};
 ArrayList<Round> data=new ArrayList<>();TextView count,stats,analysis,numbers,last,trans,patternOut;EditText pattern;String dc="A♠",tc="A♥";static class Round{String d,t,r;Round(String d,String t,String r){this.d=d;this.t=t;this.r=r;}}
 public void onCreate(Bundle b){super.onCreate(b);load();makeUi();render();}protected void onResume(){super.onResume();if(count!=null){load();render();}}
 TextView T(String x,int z){TextView v=new TextView(this);v.setText(x);v.setTextColor(Color.WHITE);v.setTextSize(z);v.setPadding(10,8,10,8);return v;}GradientDrawable G(int c,int s){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(18);g.setStroke(2,s);return g;}LinearLayout Pnl(){LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(12,10,12,12);p.setBackground(G(Color.rgb(8,42,70),Color.CYAN));LinearLayout.LayoutParams l=new LinearLayout.LayoutParams(-1,-2);l.setMargins(0,7,0,0);p.setLayoutParams(l);return p;}Button B(String x,int c){Button b=new Button(this);b.setText(x);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setBackground(G(c,Color.CYAN));return b;}
 void makeUi(){ScrollView sv=new ScrollView(this);sv.setBackgroundColor(Color.rgb(3,18,32));LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(10,8,10,20);sv.addView(root);setContentView(sv);TextView h=T("DRAGON TIGER\nPREDICTION",26);h.setGravity(17);h.setTypeface(null,Typeface.BOLD);h.setTextColor(Color.CYAN);root.addView(h);count=T("",15);count.setGravity(17);root.addView(count);stats=T("",14);stats.setGravity(17);stats.setBackground(G(Color.rgb(8,55,90),Color.MAGENTA));root.addView(stats);
 LinearLayout a=Pnl();a.addView(T("HISTORICAL RESULT ANALYSIS",18));analysis=T("",18);analysis.setGravity(17);a.addView(analysis);root.addView(a);
 LinearLayout n=Pnl();n.addView(T("NEW ROUND • A–K PLAYING CARDS",18));n.addView(T("A=1 ... K=13 • higher rank wins • equal rank = TIE",12));LinearLayout sides=new LinearLayout(this);Button d=B("DRAGON\n"+dc,Color.rgb(0,120,190)),t=B("TIGER\n"+tc,Color.rgb(180,105,0));sides.addView(d,new LinearLayout.LayoutParams(0,105,1));sides.addView(t,new LinearLayout.LayoutParams(0,105,1));n.addView(sides);Button add=B("ADD RESULT • AUTO WINNER",Color.rgb(0,145,100));n.addView(add);root.addView(n);d.setOnClickListener(v->pick(true,d));t.setOnClickListener(v->pick(false,t));add.setOnClickListener(v->add());
 LinearLayout tools=Pnl();tools.addView(T("HISTORY TOOLS",18));Button edit=B("EDIT SAVED ROUND",Color.rgb(45,95,150)),bulk=B("UPLOAD EXCEL / CSV",Color.rgb(45,95,150)),clear=B("CLEAR ALL",Color.rgb(130,45,55));tools.addView(edit);tools.addView(bulk);tools.addView(clear);root.addView(tools);edit.setOnClickListener(v->editDialog());bulk.setOnClickListener(v->startActivity(new Intent(this,ImportActivity.class)));clear.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Clear history?").setPositiveButton("CLEAR",(x,w)->{getSharedPreferences(P,0).edit().clear().apply();data.clear();render();}).setNegativeButton("CANCEL",null).show());
 LinearLayout np=Pnl();np.addView(T("NEXT NUMBER • HISTORICAL FREQUENCY",18));numbers=T("",14);np.addView(numbers);root.addView(np);
 LinearLayout pp=Pnl();pp.addView(T("D/T PATTERN FINDER",18));pp.addView(T("Search exact sequence newest → oldest: DDTTDDTT, DTDTDT",12));pattern=new EditText(this);pattern.setHint("Enter D/T pattern");pattern.setTextColor(Color.WHITE);pattern.setHintTextColor(Color.LTGRAY);pattern.setSingleLine(true);pp.addView(pattern);Button find=B("FIND EXACT PATTERN",Color.rgb(0,105,160));pp.addView(find);patternOut=T("",14);pp.addView(patternOut);root.addView(pp);find.setOnClickListener(v->findPattern());
 LinearLayout pair=Pnl();pair.addView(T("PAIR ANALYSIS",18));pair.addView(T("Search a Dragon/Tiger number pair in all saved rounds",12));Button pairBtn=B("OPEN PAIR ANALYSIS",Color.rgb(0,125,170));pair.addView(pairBtn);root.addView(pair);pairBtn.setOnClickListener(v->pairAnalysis());
 LinearLayout lr=Pnl();lr.addView(T("LAST RESULTS • NEWEST ON LEFT",18));last=T("",14);lr.addView(last);root.addView(lr);LinearLayout tr=Pnl();tr.addView(T("CARD / NUMBER TRANSITIONS",18));trans=T("",14);tr.addView(trans);root.addView(tr);}
 void pick(boolean dragon,Button b){String[] c=new String[52];int k=0;for(String r:R)for(String s:S)c[k++]=r+s;new AlertDialog.Builder(this).setTitle(dragon?"SELECT DRAGON CARD":"SELECT TIGER CARD").setItems(c,(x,w)->{if(dragon){dc=c[w];b.setText("DRAGON\n"+dc);}else{tc=c[w];b.setText("TIGER\n"+tc);}}).show();}
 String rank(String c){for(String r:R)if(c.startsWith(r))return r;return "A";}int val(String r){for(int i=0;i<R.length;i++)if(R[i].equals(r))return i+1;return 0;}String win(String d,String t){int a=val(rank(d)),b=val(rank(t));return a>b?"D":b>a?"T":"SAME";}String lab(String r){return "D".equals(r)?"DRAGON":"T".equals(r)?"TIGER":"TIE";}
 void add(){if(dc.equals(tc)){Toast.makeText(this,"Choose different cards.",Toast.LENGTH_SHORT).show();return;}data.add(new Round(rank(dc),rank(tc),win(dc,tc)));save();render();}
 void load(){data.clear();String s=getSharedPreferences(P,0).getString(K,"");if(s.isEmpty())s=initial();for(String x:s.split(";")){String[] a=x.split(",");if(a.length>=4)data.add(new Round(a[1],a[2],a[3]));}}
 String initial(){StringBuilder b=new StringBuilder();try{BufferedReader r=new BufferedReader(new InputStreamReader(getResources().openRawResource(com.fastazz.dragontiger.R.raw.historical_505)));String l;while((l=r.readLine())!=null){l=l.trim();if(!l.isEmpty()){if(b.length()>0)b.append(';');b.append(l);}}r.close();}catch(Exception e){}return b.toString();}
 void save(){StringBuilder b=new StringBuilder();for(int i=0;i<data.size();i++){if(i>0)b.append(';');Round r=data.get(i);b.append(i+1).append(',').append(r.d).append(',').append(r.t).append(',').append(r.r);}getSharedPreferences(P,0).edit().putString(K,b.toString()).apply();}
 void render(){int d=0,t=0,e=0;for(Round r:data){if("D".equals(r.r))d++;else if("T".equals(r.r))t++;else e++;}count.setText("HISTORICAL ROUNDS: "+data.size());stats.setText("🔵 DRAGON "+d+"     🟢 TIE "+e+"     🔴 TIGER "+t);analysis.setText(data.isEmpty()?"NO HISTORY":"Reference frequency: DRAGON "+d+" / TIGER "+t+" / TIE "+e);StringBuilder s=new StringBuilder();for(int i=data.size()-1;i>=Math.max(0,data.size()-10);i--){if(s.length()>0)s.append("   |   ");Round r=data.get(i);s.append(i+1).append(" ").append("D".equals(r.r)?"🔵":"T".equals(r.r)?"🔴":"🟢").append(" ").append(r.d).append('/').append(r.t);}last.setText(s.toString());numbers.setText(numFreq());trans.setText(transitions());}
 String numFreq(){int[] d=new int[13],t=new int[13];for(Round r:data){d[val(r.d)-1]++;t[val(r.t)-1]++;}StringBuilder s=new StringBuilder();for(int i=0;i<13;i++){if(i>0)s.append(" • ");s.append(R[i]).append(":D").append(d[i]).append("/T").append(t[i]);}return s.toString();}String transitions(){if(data.size()<2)return "Need 2+ rounds.";int dd=0,dt=0,td=0,tt=0;for(int i=1;i<data.size();i++){String a=data.get(i-1).r,b=data.get(i).r;if("D".equals(a)&&"D".equals(b))dd++;if("D".equals(a)&&"T".equals(b))dt++;if("T".equals(a)&&"D".equals(b))td++;if("T".equals(a)&&"T".equals(b))tt++;}return "D→D "+dd+" | D→T "+dt+" | T→D "+td+" | T→T "+tt;}
 void findPattern(){String q=pattern.getText().toString().toUpperCase(Locale.US).replaceAll("[^DT]","");if(q.length()<2){patternOut.setText("Enter at least 2 letters D/T.");return;}int hits=0;StringBuilder rounds=new StringBuilder(),newer=new StringBuilder();for(int i=data.size()-1;i>=q.length()-1;i--){boolean ok=true;for(int j=0;j<q.length();j++)if(!q.substring(j,j+1).equals(data.get(i-j).r)){ok=false;break;}if(ok){hits++;if(rounds.length()>0)rounds.append(",");rounds.append(i+1);String n=i+1<data.size()?data.get(i+1).r:"-";if(newer.length()>0)newer.append(",");newer.append("D".equals(n)?"DRAGON":"T".equals(n)?"TIGER":"SAME".equals(n)?"TIE":"-");}}patternOut.setText("Pattern "+q+" • EXACT MATCHES: "+hits+(hits>0?"\nStart rounds: "+rounds+"\nImmediately newer results: "+newer:"\nNo exact historical match."));}
 void editDialog(){if(data.isEmpty())return;String[] a=new String[data.size()];for(int i=0;i<data.size();i++){Round r=data.get(i);a[data.size()-1-i]="Round "+(i+1)+" • "+r.d+" / "+r.t+" • "+lab(r.r);}new AlertDialog.Builder(this).setTitle("SELECT ROUND").setItems(a,(x,w)->edit(data.size()-1-w)).show();}
 void edit(int idx){Round old=data.get(idx);String[] c=new String[52];int k=0;for(String r:R)for(String s:S)c[k++]=r+s;LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);Spinner d=new Spinner(this),t=new Spinner(this);d.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,c));t.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,c));d.setSelection(find(c,old.d));t.setSelection(find(c,old.t));box.addView(T("Dragon card",14));box.addView(d);box.addView(T("Tiger card",14));box.addView(t);new AlertDialog.Builder(this).setTitle("EDIT ROUND "+(idx+1)).setView(box).setPositiveButton("SAVE",(x,w)->{String dc=c[d.getSelectedItemPosition()],tc=c[t.getSelectedItemPosition()];if(dc.equals(tc))return;data.set(idx,new Round(rank(dc),rank(tc),win(dc,tc)));save();render();}).setNegativeButton("CANCEL",null).show();}
 int find(String[] c,String r){for(int i=0;i<c.length;i++)if(c[i].startsWith(r))return i;return 0;}

 void pairAnalysis(){String[] pairs=new String[169];int k=0;for(String d:R)for(String t:R)pairs[k++]=d+" / "+t; LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);list.setPadding(8,4,8,8); ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setLayoutParams(new ViewGroup.LayoutParams(-1,Math.min(900,(int)(getResources().getDisplayMetrics().heightPixels*0.72f)))); scroll.addView(list); for(int i=0;i<pairs.length;i++){final int idx=i; Button b=B(pairs[i],Color.rgb(0,105,160)); b.setTextSize(15); b.setGravity(Gravity.CENTER); LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,52); lp.setMargins(0,3,0,3); list.addView(b,lp); b.setOnClickListener(v->{String[] pt=pairs[idx].split(" / ");showPairResult(pt[0],pt[1]);});} new AlertDialog.Builder(this).setTitle("PAIR ANALYSIS • SELECT D/T NUMBERS").setView(scroll).setNegativeButton("CANCEL",null).show();}
 void showPairResult(String d,String t){int hits=0,dw=0,tw=0,ties=0;ArrayList<Integer> ids=new ArrayList<>();for(int i=0;i<data.size();i++){Round r=data.get(i);if(r.d.equals(d)&&r.t.equals(t)){hits++;ids.add(i+1);if("D".equals(r.r))dw++;else if("T".equals(r.r))tw++;else ties++;}}StringBuilder s=new StringBuilder();s.append("PAIR: DRAGON ").append(d).append(" / TIGER ").append(t).append("\\n\\n");s.append("TOTAL OCCURRENCES: ").append(hits).append("\\n");s.append("DRAGON: ").append(dw).append("   TIGER: ").append(tw).append("   TIE: ").append(ties).append("\\n\\n");if(hits>0){s.append("MATCHING ROUND IDs: ");int from=Math.max(0,ids.size()-15);for(int i=from;i<ids.size();i++){if(i>from)s.append(", ");s.append(ids.get(i));}s.append("\\n\\n");int last=ids.get(ids.size()-1);if(last<data.size()-1)s.append("NEXT RESULT AFTER LATEST MATCH: ").append(lab(data.get(last+1).r));else s.append("NEXT RESULT: NOT AVAILABLE (latest round)");}else s.append("NO MATCHING PAIR FOUND IN SAVED HISTORY.");new AlertDialog.Builder(this).setTitle("PAIR ANALYSIS RESULT").setMessage(s.toString()).setPositiveButton("OK",null).show();}
}
