package com.fastazz.dragontiger;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.widget.*;import java.util.*;

public class EditActivity extends Activity {
 static final String PREF="rounds"; ArrayList<String[]> rows=new ArrayList<>(); LinearLayout root;
 final String[] RANKS={"A","2","3","4","5","6","7","8","9","10","J","Q","K"}; final String[] SUITS={"♠","♥","♣","♦"};
 @Override public void onCreate(Bundle b){super.onCreate(b);load();build();}
 void load(){String s=getSharedPreferences("MainActivity_preferences",MODE_PRIVATE).getString(PREF,"");for(String x:s.split(";")){if(x.trim().isEmpty())continue;String[] a=x.split(",");if(a.length==4)rows.add(new String[]{a[0],a[1],a[2],a[3]});else if(a.length==3)rows.add(new String[]{String.valueOf(rows.size()+1),a[0],a[1],a[2]});}}
 void build(){ScrollView sv=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(12,12,12,30);root.setBackgroundColor(Color.rgb(3,18,32));sv.addView(root);TextView title=new TextView(this);title.setText("EDIT HISTORICAL ROUNDS");title.setTextSize(24);title.setTextColor(Color.CYAN);title.setGravity(17);title.setPadding(8,12,8,18);root.addView(title);TextView info=new TextView(this);info.setText("Tap EDIT on any round. Winner is automatic: higher rank wins; equal rank = TIE.\nA = 1 (smallest) • K = 13 (biggest)");info.setTextColor(Color.WHITE);info.setTextSize(14);root.addView(info);for(int i=rows.size()-1;i>=0;i--)addRow(i);setContentView(sv);}
 void addRow(int index){String[] r=rows.get(index);LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.HORIZONTAL);p.setPadding(6,5,6,5);TextView v=new TextView(this);v.setText("#"+r[0]+"   "+r[1]+" vs "+r[2]+"   "+label(r[3]));v.setTextColor(Color.WHITE);v.setTextSize(15);p.addView(v,new LinearLayout.LayoutParams(0,58,1));Button e=new Button(this);e.setText("EDIT");p.addView(e,new LinearLayout.LayoutParams(95,58));e.setOnClickListener(x->edit(index));root.addView(p);}
 String label(String r){return "SAME".equals(r)?"TIE":r;}
 String[] cards(){String[] a=new String[52];int k=0;for(String r:RANKS)for(String s:SUITS)a[k++]=r+s;return a;}
 int val(String r){if(r.equals("A"))return 1;if(r.equals("J"))return 11;if(r.equals("Q"))return 12;if(r.equals("K"))return 13;return Integer.parseInt(r);}
 void edit(int index){String[] old=rows.get(index);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(20,5,20,5);Spinner d=new Spinner(this),t=new Spinner(this);ArrayAdapter<String> ad=new ArrayAdapter<>(this,android.R.layout.simple_spinner_item,cards());d.setAdapter(ad);t.setAdapter(ad);String od=old[1],ot=old[2];for(int i=0;i<ad.getCount();i++){if(ad.getItem(i).startsWith(od))d.setSelection(i);if(ad.getItem(i).startsWith(ot))t.setSelection(i);}box.addView(labelView("DRAGON CARD"));box.addView(d);box.addView(labelView("TIGER CARD"));box.addView(t);TextView auto=labelView("RESULT: "+winner(od,ot));box.addView(auto);d.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?> a){}public void onItemSelected(android.widget.AdapterView<?> a,android.view.View v,int p,long id){auto.setText("RESULT: "+winner((String)d.getSelectedItem(),(String)t.getSelectedItem()));}});t.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?> a){}public void onItemSelected(android.widget.AdapterView<?> a,android.view.View v,int p,long id){auto.setText("RESULT: "+winner((String)d.getSelectedItem(),(String)t.getSelectedItem()));}});new AlertDialog.Builder(this).setTitle("EDIT ROUND #"+old[0]).setView(box).setPositiveButton("SAVE",(q,w)->{String dc=(String)d.getSelectedItem(),tc=(String)t.getSelectedItem();old[1]=rank(dc);old[2]=rank(tc);old[3]=winnerCode(dc,tc);save();recreate();}).setNegativeButton("CANCEL",null).show();}
 TextView labelView(String s){TextView v=new TextView(this);v.setText(s);v.setTextColor(Color.WHITE);v.setTextSize(14);v.setPadding(4,8,4,4);return v;}
 String rank(String c){return c.substring(0,c.length()-1);} String winner(String d,String t){int a=val(rank(d)),b=val(rank(t));return a>b?"DRAGON":b>a?"TIGER":"TIE";} String winnerCode(String d,String t){int a=val(rank(d)),b=val(rank(t));return a>b?"D":b>a?"T":"SAME";}
 void save(){StringBuilder s=new StringBuilder();for(String[] r:rows){if(s.length()>0)s.append(';');s.append(r[0]).append(',').append(r[1]).append(',').append(r[2]).append(',').append(r[3]);}getSharedPreferences("MainActivity_preferences",MODE_PRIVATE).edit().putString(PREF,s.toString()).apply();}
}
