package com.biharsurvey.nonit;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Bitmap;
import android.location.*;
import android.net.Uri;
import android.os.*;
import android.provider.MediaStore;
import android.view.*;
import android.widget.*;
import androidx.activity.result.*;
import androidx.activity.result.contract.ActivityResultContracts;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.content.ContextCompat;
import androidx.core.content.FileProvider;
import com.google.mlkit.vision.common.InputImage;
import com.google.mlkit.vision.text.TextRecognition;
import com.google.mlkit.vision.text.latin.TextRecognizerOptions;
import com.google.mlkit.vision.label.ImageLabeling;
import com.google.mlkit.vision.label.defaults.ImageLabelerOptions;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import java.io.*;
import java.text.SimpleDateFormat;
import java.util.*;

public class MainActivity extends AppCompatActivity {
 static final String APP="BIHAR SURVEY NON IT", LOGIN_ID="ADMIN", LOGIN_PASSWORD="ADMIN";
 LinearLayout root,body; EditText office,section,surveyor; TextView gps; Bitmap lastPhoto; double lat,lon; String activeCategory="Building",suggestedType="";
 ArrayList<Entry> batch=new ArrayList<>();
 final String[] categories={"Building","Office Land","Office Equipment","Office Furniture","Residential Colony","Vehicle","Plant & Machinery","Store Inventory","Edit/Rejected Entry"};
 final Map<String,String[]> HEADERS=new LinkedHashMap<>();
 static class Entry { String category,photoPath=""; LinkedHashMap<String,String> values=new LinkedHashMap<>(); double lat,lon; long time; }
 final ActivityResultLauncher<Intent> camera=registerForActivityResult(new ActivityResultContracts.StartActivityForResult(),r->{if(r.getResultCode()==RESULT_OK&&r.getData()!=null){lastPhoto=(Bitmap)r.getData().getExtras().get("data");runVision();}});
 final ActivityResultLauncher<String[]> perms=registerForActivityResult(new ActivityResultContracts.RequestMultiplePermissions(),r->updateGps());

 @Override public void onCreate(Bundle b){super.onCreate(b);buildHeaders();if(!loggedIn()){login();return;}home();requestPerms();}
 void buildHeaders(){
  HEADERS.put("Building", new String[]{"Unique Id","ENTRYDATE","Surveyor","Hierarchylevel","Discom/ Organization Name","Zone Name","Circle Name","Division Name","Subdivision Name","Section Name","State","District Name","Block Name","Gram Panchyat Name","Village Name","Pincode","Building Type","Building Name","Building Type Other","Year Constructed","Owenership","Office Name","Colony Name","No of Quarter","No of Households per Floor","No of Floor","Area Unit","Builtup Area","Condititon","Address","Fire Safety","Power Connection","Lift Available","Occupancy","Scheme Name","Registration Date Available","Registry No","Registration Date","In-Operational Date","Verified Date","Status","Remarks","Name1","Value1","Name2","Value2","Name3","Value3","Name4","Value4","Name5","Value5"});
  HEADERS.put("Office Land", new String[]{"Unique Id","ENTRYDATE","Surveyor","HierarchyLevel","Discom/ Organization Name","Zone Name","Circle Name","Division Name","Subdivision Name","Sectio Name","State","District Name","Block Name","Gram Panchyat Name","Village Name","Pin Code","Land Type","Land Ownership","Office Land Type Other","Land Uses","Record Id","Plot No","Area Unit","Area Acres","Survey Number","Land North","Land South","LAND East","Land West","Document Refrence","Condition","Status","Encriachment","Legal Status","Remarks","Scheme Name","Is Registration Date","Registry No","Registration Date","Doc Reference","Address","Name1","Value1","Name2","Value2","Name3","Value3","Name4","Value4","Name5","Value5"});
  HEADERS.put("Office Equipment", new String[]{"Unique Id","ENTRYDATE","Surveyor","Hierarchy","Discom/ Organization Name","Zone Name","Circle Name","Division Name","Subdivision Name","Section Name","State","District Name","Block Name","Gram Panchyat Name","Village Name","Pincode","Store","Building Name","Status","Room Section","Asset Lifecycle Status","Equipment Type","Fan Type","Motor Hub","Cooler Type","Size","Capacity","Working condition","Filter condition","Heater Type","Wattage","Installed Capacity DC","Rated AC Power","Module Technology","Mounting Technology","Number of Modules","Number of Inverters","Inverter Rated Power","Commissioning Date","Grid Connection Type","Effective Roof Area","Installation Type","Solar Condition","Office Name","Condition","Scheme Name","Floor","Manufacturing Date","Model Name","Remarks","Warranty Expiry Date","Serial Number","Warranty","Purchase Order Number","Purchase Order Date","AMC","Manufacturing Name","feature Code","Census Code","AMC Expiry Date","Date of Commissioning","Residual Value","In-operational Date","Building","Address","Storage","Equipment Number","Ram","Graphics Card","Designation","Processor","AC Type","Used by Person Name","AC Capacity","Model No","Printer Size","Ac Type Other","Equipment Type Other","Name1","Value1","Name2","Value2","Name3","Value3","Name4","Value4","Name5","Value5","Starting Method","Temperature Rise","Degree Protection","Battery Quantity","Rated Voltage","Generator Model","Excitation Type","No of Phases","Charger Output","Governor Type","Battery Type","Insulation Class","Neutral Formation","Fuel Type","Frequency HZ","Overload Capacity","Terminal Box","Engine Type","Rated RPM","Battery Voltage","Aspiration Type","Charger Type","Fuel Pump Type","Cooling Type","Generator Type","Power Factor","Generator Capacity KVA","Battery Capacity","Fuel Injection"," Fuel Tank Capacity","Location","Cable Size","LOA Number","Noise Level","Acoustic Material","Lubricanting System","Mounting Type","Loa Date","Cylinder Pressure Bar","Hose Temperature Range","Lancing Distance","Face Mask Type","Fire Rating","SCBA Available","Cylinder Material","Extinguising Medium","Nozzle Type","Cylinder Type","Foam Type","Pressure Gauge","fire Capacity","Totalweight KG"," Working Duration Min","Fire Extinguisher Type","Back Plate Type","Warning Wristle","Maximum Operating Temperature","Minimum Operating Temperature","Pressure Reducer","Laboratory Test"});
  HEADERS.put("Office Furniture", new String[]{"Unique Id","ENTRYDATE","Surveyor","Hierarchy","Discom","Zone Name","Circle Name","Division Name","Subdivision Name","Section Name","State","District Name","Block Name","Gram Panchyat Name","Village Name","Pincode","Building","Office","Store","Floor","Room Section","Model","Equipment Type","Manufacturer Name","Condition","Assetstatus","Manufacturingdate","Quantity","Material","Eam","Feature Code","Census","Status","Remarks","In-Operational Date","Approved By","Amc Date","Warranty","Purchase Order No","Purshase Order Date","Warranty Date","Amc","Residual Value","Date Commission","Item Type","Bed Size","Bed Material","Bed Conditon","Working Usable","Building Name","Address","Designation","Used by","Schema Name","New Address","Table Type","Seater","Size","Other Item Type","Name1","Value1","Name2","Value2","Name3","Value3","Name4","Value4","Name5","Value5"});
  HEADERS.put("Residential Colony", new String[]{"Unique Id","ENTRYDATE","Surveyor","Hierarchy","Discom/ Organization Name","Zone Name","Circle Name","Division Name","Subdivision Name","Section Name","State","District Name","Block Name","Gram Panchyat Name","Village Name","Pincode","Feature Code","Address","Store Name","Serial Number","Gis Unique Id","Area Acres","Land Type","Residual Value","Condition","Legal Status","Status","Encroachment","Commissioning Date","In-Operational Date","Scheme Name","Registration Date","Purchase Order Date","Remarks","Purchase Number","House Type","Parking","No of House/Flat","Colony Name","Fitness Valid Date","Registry No","Is Registration Date Available","Colony Type","Colony Type Other","House Type Other","Name1","Value1","Name2","Value2","Name3","Value3","Name4","Value4","Name5","Value5"});
 }
 boolean loggedIn(){return getPreferences(0).getBoolean("login",false);}
 void login(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(36,70,36,30);root.setBackgroundColor(0xfff4f7fb);root.addView(title(APP));root.addView(title("Common Login"));EditText u=input("Login ID");EditText p=input("Password");p.setInputType(129);root.addView(u);root.addView(p);Button b=btn("LOGIN");root.addView(b);b.setOnClickListener(v->{if(LOGIN_ID.equals(u.getText().toString().trim())&&LOGIN_PASSWORD.equals(p.getText().toString())){getPreferences(0).edit().putBoolean("login",true).apply();home();requestPerms();}else Toast.makeText(this,"Invalid common login",Toast.LENGTH_SHORT).show();});setContentView(root);}
 void home(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(0xfff4f7fb);LinearLayout bar=new LinearLayout(this);bar.setPadding(18,18,18,12);bar.addView(title(APP),new LinearLayout.LayoutParams(0,-2,1));Button ex=btn("EXPORT EXCEL");bar.addView(ex);root.addView(bar);ex.setOnClickListener(v->exportExcel());ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(18,5,18,30);sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);for(String c:categories){Button x=btn(c);body.addView(x,new LinearLayout.LayoutParams(-1,60));x.setOnClickListener(v->{if(c.equals("Edit/Rejected Entry"))showSaved();else if(HEADERS.containsKey(c))form(c);else Toast.makeText(this,"Excel fields for this category are not supplied yet.",Toast.LENGTH_LONG).show();});}}
 void form(String cat){activeCategory=cat;batch.clear();body.removeAllViews();body.addView(title(cat));office=input("Office / Location (saved for this batch)");section=input("Section (Accounts / RO Office / JEE Office / etc.)");surveyor=input("Surveyor name");body.addView(office);body.addView(section);body.addView(surveyor);gps=new TextView(this);gps.setText("GPS: waiting...");body.addView(gps);Button cam=btn("TAKE ITEM PHOTO + OCR / IDENTIFY");body.addView(cam);cam.setOnClickListener(v->camera.launch(new Intent(MediaStore.ACTION_IMAGE_CAPTURE)));Button add=btn("ADD ITEM TO BATCH");body.addView(add);add.setOnClickListener(v->addItem(cat));Button preview=btn("BATCH OVERVIEW / SAVE");body.addView(preview);preview.setOnClickListener(v->preview());Button back=btn("BACK HOME");body.addView(back);back.setOnClickListener(v->home());}
 void addItem(String cat){if(lastPhoto==null){Toast.makeText(this,"Photo mandatory.",Toast.LENGTH_SHORT).show();return;}if(lat==0&&lon==0){Toast.makeText(this,"GPS mandatory. Enable location.",Toast.LENGTH_SHORT).show();return;}Entry e=new Entry();e.category=cat;e.lat=lat;e.lon=lon;e.time=System.currentTimeMillis();for(String k:HEADERS.get(cat))e.values.put(k,"");String sec=section.getText().toString(),loc=office.getText().toString();e.values.put("Surveyor",surveyor.getText().toString());e.values.put("Section Name",sec);e.values.put("Room Section",sec);e.values.put("Address",loc);e.values.put("Building Name",loc);e.values.put("Office",loc);e.values.put("ENTRYDATE",new SimpleDateFormat("yyyy-MM-dd HH:mm:ss",Locale.US).format(new Date(e.time)));e.values.put("Item Type",suggestedType);e.values.put("Equipment Type",suggestedType);e.values.put("Unique Id",String.valueOf(System.currentTimeMillis()));e.photoPath=e.values.get("Unique Id")+".jpg";batch.add(e);lastPhoto=null;Toast.makeText(this,"Item added. Total: "+batch.size(),Toast.LENGTH_SHORT).show();}
 void runVision(){if(lastPhoto==null)return;InputImage img=InputImage.fromBitmap(lastPhoto,0);TextRecognition.getClient(TextRecognizerOptions.DEFAULT_OPTIONS).process(img).addOnSuccessListener(r->{String t=r.getText();suggestedType=t.isEmpty()?"":t;ImageLabeling.getClient(ImageLabelerOptions.DEFAULT_OPTIONS).process(img).addOnSuccessListener(labels->{if(suggestedType.isEmpty()&&!labels.isEmpty())suggestedType=labels.get(0).getText();Toast.makeText(this,"Detected: "+(suggestedType.isEmpty()?"Review manually":suggestedType),Toast.LENGTH_LONG).show();});});}
 void preview(){if(batch.isEmpty()){Toast.makeText(this,"No item added.",Toast.LENGTH_SHORT).show();return;}new AlertDialog.Builder(this).setTitle("BATCH OVERVIEW").setMessage("Items: "+batch.size()+"\nCategory: "+activeCategory+"\nOffice: "+office.getText()+"\nSection: "+section.getText()+"\n\nPhoto + GPS + date/time are mandatory.").setNegativeButton("CANCEL",null).setPositiveButton("CONFIRM & SAVE",(d,w)->saveBatch()).show();}
 void saveBatch(){ArrayList<String>s=new ArrayList<>(getPreferences(0).getStringSet("saved",new HashSet<>()));for(Entry e:batch)s.add(e.category+"|"+e.values.get("Unique Id")+"|"+e.values.get("Item Type")+"|"+e.values.get("Address")+"|"+e.lat+","+e.lon+"|"+new SimpleDateFormat("yyyy-MM-dd HH:mm:ss",Locale.US).format(new Date(e.time)));getPreferences(0).edit().putStringSet("saved",new HashSet<>(s)).apply();batch.clear();Toast.makeText(this,"Batch saved successfully.",Toast.LENGTH_LONG).show();home();}
 void showSaved(){Set<String>s=getPreferences(0).getStringSet("saved",new HashSet<>());StringBuilder b=new StringBuilder();for(String x:s)b.append(x).append("\n\n");new AlertDialog.Builder(this).setTitle("SAVED / REJECTED ENTRIES").setMessage(b.length()==0?"No saved entries.":b.toString()).setPositiveButton("OK",null).show();}
 void exportExcel(){Set<String>s=getPreferences(0).getStringSet("saved",new HashSet<>());if(s.isEmpty()){Toast.makeText(this,"No saved data.",Toast.LENGTH_SHORT).show();return;}try{Workbook wb=new XSSFWorkbook();Map<String,Sheet>m=new HashMap<>();for(String c:HEADERS.keySet()){Sheet ws=wb.createSheet(c);m.put(c,ws);Row h=ws.createRow(0);int i=0;for(String x:HEADERS.get(c))h.createCell(i++).setCellValue(x);for(String x:new String[]{"Latitude","Longitude","Photo Link","Item Identity","Survey Date","Survey Time"})h.createCell(i++).setCellValue(x);}for(String line:s){String[]p=line.split("\\|",-1);Sheet ws=m.get(p[0]);if(ws==null)continue;Row r=ws.createRow(ws.getLastRowNum()+1);r.createCell(0).setCellValue(p.length>1?p[1]:"");r.createCell(1).setCellValue(p.length>5?p[5]:"");r.createCell(2).setCellValue("Survey");int n=HEADERS.get(p[0]).length;r.createCell(n).setCellValue(p.length>4?p[4].split(",")[0]:"");r.createCell(n+1).setCellValue(p.length>4?p[4].split(",")[1]:"");r.createCell(n+2).setCellValue(p.length>2?p[2]:"");r.createCell(n+3).setCellValue(p.length>2?p[2]:"");r.createCell(n+4).setCellValue(p.length>5?p[5].substring(0,10):"");r.createCell(n+5).setCellValue(p.length>5?p[5].substring(11):"");}File out=new File(getExternalFilesDir(null),"BIHAR_SURVEY_NON_IT.xlsx");FileOutputStream f=new FileOutputStream(out);wb.write(f);f.close();wb.close();Intent i=new Intent(Intent.ACTION_SEND);i.setType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");i.putExtra(Intent.EXTRA_STREAM,FileProvider.getUriForFile(this,"com.biharsurvey.nonit.fileprovider",out));i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(i,"Share Excel"));}catch(Exception e){Toast.makeText(this,"Excel export failed: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
 void requestPerms(){perms.launch(new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION,Manifest.permission.CAMERA});}
 void updateGps(){if(ContextCompat.checkSelfPermission(this,Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED){if(gps!=null)gps.setText("GPS permission required");return;}LocationManager lm=(LocationManager)getSystemService(LOCATION_SERVICE);Location l=lm.getLastKnownLocation(LocationManager.GPS_PROVIDER);if(l==null)l=lm.getLastKnownLocation(LocationManager.NETWORK_PROVIDER);if(l!=null){lat=l.getLatitude();lon=l.getLongitude();if(gps!=null)gps.setText("GPS: "+lat+", "+lon);}else if(gps!=null)gps.setText("GPS: waiting...");}
 TextView title(String s){TextView t=new TextView(this);t.setText(s);t.setTextColor(0xff17324d);t.setTextSize(22);t.setTypeface(null,1);t.setPadding(4,12,4,12);return t;}
 EditText input(String h){EditText e=new EditText(this);e.setHint(h);e.setTextSize(16);e.setPadding(14,8,14,8);return e;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(14);return b;}
}